### ISSUE TITLE
Graph inputs should be full graph not splits, rename example paths

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/NEAT#3]
These two variables in the main yaml section suggest a split training set:

node_path: tests/resources/test_graphs/pos_train_nodes.tsv
edge_path: tests/resources/test_graphs/pos_train_edges.tsv

I imagine these are just placeholder paths but for a better example could indicate that these are the full graph edges and nodes.

**Comment by justaddcoffee** [comment]
The yaml file here: `tests/resources/test.yaml` describes graph ML on a test/train split, not the full graph
