### ISSUE TITLE
some way to handle singleton nodes in graph input and resulting embeddings

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/NEAT#4]
Embiggen will embed every node in the node file OR all non-singleton nodes in the edge (when no node file is provided). Maybe we can help shepherd this in the right direction. The ensmallen output includes singleton count so in theory the pipeline could be aware at that stage. By default it may be best to embed all nodes (hence require the node file), however then can include noninformative embedding for singleton nodes in the output, so perhaps another output file (eg npy) excluding singletons would help here or some way to indicate the uninformative embeddings.

**Comment by justaddcoffee** [comment]
Filtering singletons before or after embedding might be useful, but probably not in scope for NEAT, at least not now with limited bandwidth.
