### ISSUE TITLE
add parameters for NEAT embedding output file naming, format, and ensure that node identifiers part of any embedding output

### ISSUE THREAD

**Issue by realmarcin** [Knowledge-Graph-Hub/NEAT#5]
There could be a few more parameters for handling the embedding outputs, eg:

- file name
- file format (default is .npy now, but .tsv could be a good option aka easy file validation)
- tracking node identifiers from input files to these outputs

**Comment by justaddcoffee** [comment]
File name and extension are set by user - no plans to change this. 

Node CURIEs should be output with embeddings now
