### ISSUE TITLE
Use LinkML to parse and validate NEAT YAML files

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/NEAT#52]
We should consider using [LinkML](https://github.com/linkml/linkml) to validate our NEAT YAML files. Right now we are using some simple procedural code within the YamlHelper class to do this, but LinkML would provide a more sophisticated and thorough check of the YAML. 

On the other hand, this would take some time to implement, and might increase the complexity of debugging NEAT YAML validation.

Just making this ticket to discuss

**Comment by caufieldjh** [comment]
Now implemented in https://github.com/Knowledge-Graph-Hub/NEAT_schema - thanks @hrshdhgd !

Will just need a validation function for NEAT - can run during pre run checks.

**Comment by justaddcoffee** [comment]
Nice! Thanks @hrshdhgd

**Comment by caufieldjh** [comment]
Tasks: 
- [ ] Convert yaml helper to use new `neat_schema`
- [ ] Implement LinkML-driven validation of input config files
- [ ] Translate test yamls to `neat_schema`
- [ ] Add new test(s) for input validation
- [ ] Update existing tests
