### ISSUE TITLE
Move `graph_path` argument out of `graph_data` arguments

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/NEAT#76]
As seen in issues like #73, it is problematic to have an additional argument passed to a function expecting to pass all kwargs to Ensmallen. It also complicates LinkML schema design.
The `graph_path` arg can still be optional, but should be provided independent of `graph_data`.

**Comment by justaddcoffee** [comment]
thanks, makes sense, and probably will simplify supporting linkML
